name: CI

on:
  push:
  pull_request:

jobs:
  flatpak:
    name: "Flatpak CI"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: [Resolve, ResolveStudio]
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: com.blackmagic.${{ matrix.file }}
        manifest-path: com.blackmagic.${{ matrix.file }}.yaml
        cache-key: flatpak-builder-${{ matrix.file }}-${{ github.sha }}
